"""Regenerate the bundled hero/item lookup tables for the Steam-game adapters.

    python scripts/snapshot_assets.py

Writes ``clutch/games/_dota_assets.py`` (OpenDota constants) and
``clutch/games/_deadlock_assets.py`` (deadlock-api.com assets). They're
bundled rather than fetched at runtime so demo mode and the tests work
offline; rerun this when a new hero ships.
"""

from __future__ import annotations

import pprint
from pathlib import Path

import requests

OUT = Path(__file__).resolve().parents[1] / "clutch" / "games"
HEADER = '"""Generated by scripts/snapshot_assets.py — do not edit by hand."""\n\n'


def get(url: str):
    resp = requests.get(url, timeout=30, headers={"User-Agent": "clutch/0.1"})
    resp.raise_for_status()
    return resp.json()


def write(name: str, **tables) -> None:
    body = "".join(f"{key} = {pprint.pformat(value, width=120, sort_dicts=True)}\n\n" for key, value in tables.items())
    (OUT / name).write_text(HEADER + body.rstrip() + "\n", encoding="utf-8")
    print(f"wrote {name}: " + ", ".join(f"{k}={len(v)}" for k, v in tables.items()))


def dota() -> None:
    heroes = get("https://api.opendota.com/api/constants/heroes")
    items = get("https://api.opendota.com/api/constants/items")
    write(
        "_dota_assets.py",
        # id -> (display name, image slug, first listed role)
        HEROES={
            int(h["id"]): (h["localized_name"], h["name"].removeprefix("npc_dota_hero_"), (h.get("roles") or [None])[0])
            for h in heroes.values()
        },
        # id -> image slug (…/items/<slug>.png)
        ITEMS={int(i["id"]): slug for slug, i in items.items() if i.get("id") and i.get("img") and not slug.startswith("recipe_")},
    )


def deadlock() -> None:
    heroes = get("https://api.deadlock-api.com/v1/assets/heroes?only_active=true")
    ranks = get("https://api.deadlock-api.com/v1/assets/ranks")
    write(
        "_deadlock_assets.py",
        # id -> (display name, small icon URL, hero type)
        HEROES={
            h["id"]: (h["name"], h["images"].get("icon_image_small_webp") or h["images"].get("icon_image_small"), h.get("hero_type"))
            for h in heroes
        },
        RANKS={r["tier"]: r["name"] for r in ranks},
    )


if __name__ == "__main__":
    dota()
    deadlock()
